### ISSUE TITLE
TreeNSearch in Position based dynamics(PBD)

### ISSUE THREAD

**Issue by lyd405121** [InteractiveComputerGraphics/TreeNSearch#2]
- Your paper is wonderful， especially the brachless part, really get so much out of it
## Background
- Recently, I implemented  a rigidbody simulator with PBD, which learned from [papers](http://mmacklin.com/EG2015PBD.pdf)  written by interactive graphics and nvidia

[output.webm](https://user-images.githubusercontent.com/16344694/212001228-cdcec2e1-c8fc-4098-b3a6-3f022940abdc.webm)

- But just as you metioned in your paper, uniform grid usually work with particle based method 
- If I want put two rigid body into the simulator, the difference of size for them can‘t be too large
- Because the particle number is in a cubic relationship with object size，if we keep the same particle radius for all, memory will explode
- So maybe a hierarchy data structure + mixed radius size  will help and that‘s exactly your paper do in sph
- While in your paper you also mentioned TreeNSearch works not very well in the situation that objects move rapidlly

## The Question

- Is this data structure suitable for Position based dynamics , including rigidbody, cloth and fluid simulation

**Comment by JoseAntFer** [comment]
Hello,

thank you very much for your kind words. We are happy to see that people find our work interesting.

To your particular question: I always suggest to try out ideas. It is very hard to know which method is the best for each application just by thinking about it. That said, I think our approach might indeed suit your application, it is relatively easy to set up so you shouldn't need too much time. However, keep in mind that our target problem is _wildly_ different to yours: we want to find neighbors in very large simulations with millions of particles. For what I can see, you are working on real time simulations and much smaller problem (in terms of amount of data) so you may find other solutions more effective than ours.

Best regards,
José.

**Comment by lyd405121** [comment]
> Hello,
> 
> thank you very much for your kind words. We are happy to see that people find our work interesting.
> 
> To your particular question: I always suggest to try out ideas. It is very hard to know which method is the best for each application just by thinking about it. That said, I think our approach might indeed suit your application, it is relatively easy to set up so you shouldn't need too much time. However, keep in mind that our target problem is _wildly_ different to yours: we want to find neighbors in very large simulations with millions of particles. For what I can see, you are working on real time simulations and much smaller problem (in terms of amount of data) so you may find other solutions more effective than ours.
> 
> Best regards, José.

- Thank you for you advice,  I will try it out and find more potential solution.
- Learned a lot from interactive graphics， like the sdf generate Discregrid which I used in my project 

## More Info
- I start from small data and real time simulation by now which is not complicated about modern hardware achitechture
- But  large scale and offline simulator will be a long term to acheive
- Currently, we are building a system with AI to detect flood , forrest fire，debris flow, so kind of natural disaster
- It is really hard to gather such kind of data, so we aim to generate synthetic data by simulation
- Now we are using rigidbody simulation to train our robot picking task
